[package]
name = "alloy-transports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
reqwest = { version = "0.11.18", features = ["serde_json", "json"] }

futures-channel.workspace = true
jsonrpsee-types.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true

