[package]
name = "alloy-transports"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-json-rpc.workspace = true


base64 = "0.21.0"
reqwest = { version = "0.11.18", features = ["serde_json", "json"] }

futures-channel.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true
tower = { version = "0.4.13", features = ["util"] }
pin-project = "1.1.2"

