[package]
name = "alloy-transports"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-json-rpc.workspace = true

base64 = "0.21.0"

futures-channel.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true

url.workspace = true
tower.workspace = true
pin-project.workspace = true

# feature deps
reqwest = { version = "0.11.18", features = ["serde_json", "json"], optional = true }
tokio = { version = "1.33.0", features = ["sync", "macros"] }
alloy-primitives.workspace = true
bimap = "0.6.3"
tracing = "0.1.40"
futures = "0.3.29"
http = "0.2.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.hyper]
version = "0.14.27"
optional = true
features = ["full"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "1.33.0"
features = ["sync", "rt"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.37"
ws_stream_wasm = "0.7.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio-tungstenite = { version = "0.20.1", features = ["rustls-tls-webpki-roots"]}


[features]
default = ["reqwest", "hyper"]
reqwest = ["dep:reqwest"]
hyper = ["dep:hyper", "hyper/client"]

[dev-dependencies]
test-log = { version = "0.2.13", default-features = false, features = ["trace"] }
tracing-subscriber = "0.3.17"
tracing-test = "0.2.4"
