[package]
name = "ethers-next"
version = "0.1.0"
edition.workspace = true

[workspace]
members = []
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.65"
authors = []
license = "MIT OR Apache-2.0"
homepage = "https://github.com/ethers-rs/next"
repository = "https://github.com/ethers-rs/next"
