[package]
name = "network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives.workspace = true
alloy-rlp.workspace = true

alloy-transports.workspace = true

serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tower = "0.4.13"
